modLoader="javafml"
loaderVersion="*"
issueTrackerURL="https://github.com/UltimatChamp/BetterGrassify/issues"
displayURL="https://github.com/UltimatChamp/BetterGrassify"
logoFile="assets/bettergrass/icon.png"
authors="${mod_authors}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.bettergrass]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.bettergrass]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bettergrass]]
modId="fabric_api"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.bettergrass]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="bettergrass.mixins.json"
